# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='time')),
                ('inout', models.CharField(choices=[('INPUT', '\u6536\u5165'), ('OUTPUT', '\u652f\u51fa')], max_length=8)),
                ('money', models.DecimalField(decimal_places=2, max_digits=8)),
                ('memo', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='BookSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
            ],
        ),
        migrations.AddField(
            model_name='booksubtype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.BookType'),
        ),
        migrations.AddField(
            model_name='bookitem',
            name='subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.BookSubType'),
        ),
        migrations.AddField(
            model_name='bookitem',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.BookType'),
        ),
    ]
